- id: home
  mnemonic: 0
  href: /
  match: ^\/$
- id: tags
  mnemonic: 0
  href: /tags
  match: ^\/tags$
- id: photos
  mnemonic: 0
  href: /photography/1
  match: ^\/photography\/\d*|\/photography$
- id: now
  mnemonic: 0
  href: /now
  match: ^\/now$
