name: build & deploy to vercel

on:
  push:
    branches:
      - master

env:
  PRODUCTION: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ‚§µÔ∏è check out code
        uses: actions/checkout@master
        with:
          submodules: true

      - name: ‚ûï install musescore
        run: sudo apt-get install -y musescore

      - name: ‚ûï install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: ‚ûï actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: ‚ûï install node dependencies
        run: pnpm install

      - name: ‚ûï install vercel cli
        run: pnpm install --global vercel

      - name: üî∫ pull vercel environment information
        run: vercel pull --yes --environment=production
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: üî∫ build & deploy to vercel
        run: vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
